# Generated by Django 3.1.5 on 2021-01-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('data_pub', models.DateTimeField(verbose_name='data publicacao')),
            ],
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opc', models.CharField(max_length=200)),
                ('votos', models.IntegerField(default=0)),
                ('perguta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.pergunta')),
            ],
        ),
    ]
